# Generated by Django 5.0.2 on 2025-05-21 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0007_rename_fecha_realización_evento_fecha_evento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='Hora_inicio',
            new_name='hora_inicio',
        ),
    ]
