# Generated by Django 5.0.2 on 2025-05-21 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0008_rename_hora_inicio_evento_hora_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='Hora_fin',
            new_name='hora_fin',
        ),
    ]
