# Generated by Django 5.0.2 on 2025-05-21 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0009_rename_hora_fin_evento_hora_fin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='Lugar',
            new_name='lugar',
        ),
    ]
