# Generated by Django 5.0.2 on 2025-05-21 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0010_rename_lugar_evento_lugar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='Publico_objetivo',
            new_name='publico_objetivo',
        ),
    ]
