# Generated by Django 5.0.2 on 2025-05-21 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0011_rename_publico_objetivo_evento_publico_objetivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='Programa_educativo',
            new_name='programa_educativo',
        ),
    ]
