# Generated by Django 5.0.2 on 2025-05-21 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0012_rename_programa_educativo_evento_programa_educativo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='Responsable_evento',
            new_name='responsable_evento',
        ),
    ]
