# Generated by Django 5.0.2 on 2025-05-21 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0013_rename_responsable_evento_evento_responsable_evento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='Descripción_breve',
            new_name='descripcion',
        ),
    ]
