# Generated by Django 5.0.2 on 2025-05-21 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0014_rename_descripción_breve_evento_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='Cupo_máximo',
            new_name='cupo_maximo',
        ),
    ]
