# Generated by Django 5.0.2 on 2025-05-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0015_rename_cupo_máximo_evento_cupo_maximo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='hora_fin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='hora_inicio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
